tte_ext_input_create();
width = 300;
height = 30;
padding_left = 2;
padding_top = 4;
padding_right = 0;
padding_bottom = 0;
font = FTNormal;
bg = c_white;
fg = c_black;
tte_ext_input_set_multiline(false);